/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Mon Dec 31 19:01:31 2012
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_LCM_IDPIN_CHANNEL     0
#define AUXADC_UTMS_CHANNEL     3


#endif //_CUST_AUXADC_TOOL_H


